#!/bin/bash
source ./envs.sh


files=""
function init_index(){
    if [ ! -f ${index_file} ];then
        touch ${index_file}
    else
        files=($(cat ${index_file}))
    fi
}

function legit_add(){
    init_index
    files+=($*)
    files=($(echo ${files[@]} |sed 's/ /\n/g'|sort|uniq))
    cat /dev/null > $index_file
    for i in ${files[@]}
    do
        if [ ! -f $i ]; then
            echo $i " not exits"
            exit 2
        fi
        # store to index
        sha1=`sha1sum $i`
        sha1=($sha1)
        if [ ! -f $objsdir/${sha1[0]} ];then
            tar -zcvf $objsdir/${sha1[0]} $i 1>/dev/null 2>/dev/null
        fi
        echo $i >> $index_file
    done
}

if [ $# -eq 0 ]; then
    echo "Use age add files"
    exit 1
fi

legit_add $*
